name: Link Check

on: push

jobs:
  linkcheck:
    name: Link Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
    - name: Check links in README
      run: |
        npm install
        npm run linkcheck
