name: Markdown Lint

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Node.js
      uses: actions/setup-node@master
      with:
        node-version: 12.x
    - name: npm install and test
      run: |
        npm install
        npm run markdownlint
